name: "Azure DDNS (Beta)"
version: "0.1.12-PullRequest0005-0005"
slug: "azure-ddns-beta"
description: "Keeps an Azure DNS A record in sync with your public IP address"
url: https://github.com/ClassonConsultingAB/ha-azure-ddns
arch:
  - aarch64
image: "ghcr.io/classonconsultingab/ha-azure-ddns"
options:
  interval_seconds: 300
  dns_zone_resource_id: ""
  record_name: ""
  ttl_seconds: 3600
  ip_provider_endpoint: "https://icanhazip.com"
  tenant_id: ""
  client_id: ""
  client_secret: ""
schema:
  interval_seconds: "int(30,)"
  dns_zone_resource_id: "str"
  record_name: "str"
  ttl_seconds: "int(30,)"
  ip_provider_endpoint: "url"
  tenant_id: "str"
  client_id: "str"
  client_secret: "password"
